# Generated by Django 4.1.5 on 2023-01-29 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_remove_profile_id_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
