# Generated by Django 4.1.5 on 2023-01-29 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
